### ISSUE TITLE
Feature: adjust table width

### ISSUE THREAD

**Issue by GhostyCHEN** [nlulic/slate-table#1]
plz add a feature to adjust table width & height!
I need it

**Comment by nlulic** [comment]
Hello @GhostyCHEN, unfortunately, adjusting the width and height of the table is beyond the scope of this project. The aim of slate-table is to offer core features for manipulating the table's structure while remaining agnostic to the implementation of view components (similar to the core logic of slate.js).

Resizing the table and its cells should be the responsibility of the view components, which you'll need to implement yourself.

I suggest looking into [plate.js](https://platejs.org/docs/table); it provides an excellent table implementation with components already capable of adjusting both the height and width of the table cells.

**Comment by nlulic** [comment]
I'm closing this issue. If you encounter any other problems feel free to open another issue.

**Comment by nlulic** [comment]
I'm closing this issue. If you encounter any other problems feel free to open another issue.
